### ISSUE TITLE
 PDFSyntaxError('No /Root object! - Is this really a PDF?')

### ISSUE THREAD

**Issue by Canacedq** [jackiekazil/data-wrangling#10]
code like this:
`
import slate
with open('xxx.pdf') as f:
     doc = slate.PDF(f)
`
raise problem:
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Python27\lib\site-packages\slate\slate.py", line 38, in __init__
    self.doc.set_parser(self.parser)
  File "C:\Python27\lib\site-packages\pdfminer\pdfparser.py", line 333, in set_parser
    raise PDFSyntaxError('No /Root object! - Is this really a PDF?')
pdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?

**Comment by kjam** [comment]
Hi @Canacedq can you share what PDF you are using? Is it one included in the repository?

**Comment by conango** [comment]
Hi，I'm also encountered with this issue and using the exactly same PDF file downloaded from this github.
pdfminer is 20110515 ver.
and it can't run with the latest version of pdfminer.
Please have a look at this issue,thanks!

**Comment by kjam** [comment]
Hi @conango,

I'm worried this might be a Windows encoding error, as it works fine on my Linux laptop. Can you try opening the file in binary mode? 

```open('xxx.pnf', 'rb')```

Let me know if that works, thanks!

-katharine

**Comment by conango** [comment]
Hi @kjam ,
This is the result screenshot.
Hope it can help.
![qq 20180108092153](https://user-images.githubusercontent.com/8816223/34656484-d3c87d30-f455-11e7-8d3e-eac562927535.png)
Thanks

**Comment by kjam** [comment]
Hi,

Did you try and pass that to slate? so next run:

doc = slate.PDF(mypdf)

?
