### ISSUE TITLE
"Table 9" sheet  does not exist in "SOWC 2014 Stat Tables_Table 9.xlsx" 

### ISSUE THREAD

**Issue by TakesxiSximada** [jackiekazil/data-wrangling#3]
But "Table 9 " sheet exists. (Blank character at the end)
use data: https://github.com/jackiekazil/data-wrangling/blob/master/data/chp4/SOWC%202014%20Stat%20Tables_Table%209.xlsx

sample code

```
import xlrd
book = xlrd.open_workbook('SOWC 2014 Stat Tables_Table 9.xlsx')
sheet = book.sheet_by_name('Table 9')
print sheet
```

result:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    sheet = book.sheet_by_name('Table 9')
  File "/env27/lib/python2.7/site-packages/xlrd/book.py", line 441, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
xlrd.biffh.XLRDError: No sheet named <'Table 9'>

```

exists sheet name code:

```
import xlrd
book = xlrd.open_workbook('SOWC 2014 Stat Tables_Table 9.xlsx')
sheet = book.sheet_by_name('Table 9 ')  # <- MODIFIED
print sheet
```

result:

```
$ python test.py
<xlrd.sheet.Sheet object at 0x102a50f90>

```

**Comment by TakesxiSximada** [comment]
sorry.. This was was intentional.
